### ISSUE TITLE
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.suddenh4x.ratingdialog.dialog.DialogOptions)

### ISSUE THREAD

**Issue by itsniaz** [SuddenH4X/awesome-app-rating#27]
Caused by java.io.NotSerializableException: com.suddenh4x.ratingdialog.buttons.ConfirmButton
       at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
       at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
       at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
       at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)

**Comment by SuddenH4X** [comment]
Hi @itsniaz,

this bug should be fixed in version 2.2.1. Which version are you using?

**Comment by itsniaz** [comment]
I am using 2.2.0.
I will be upgrading to 2.2.1 then.

**Comment by uklertis** [comment]
Is there any update on this bug? I also have the same issue

**Comment by itsniaz** [comment]
@uklertis 
At that time i upgraded to 2.2.1 and the issue got fixed.

**Comment by Monabr** [comment]
Using 2.2.1 and still get this

**Comment by Monabr** [comment]
@SuddenH4X Also get it in 2.3.0
