### ISSUE TITLE
Crash when app is onPause

### ISSUE THREAD

**Issue by kandz** [SuddenH4X/awesome-app-rating#29]
Please help, this error appears when app is onPause(), i using 2.2.1 release version

java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.suddenh4x.ratingdialog.dialog.DialogOptions)
        at android.os.Parcel.writeSerializable(Parcel.java:1394)
        at android.os.Parcel.writeValue(Parcel.java:1341)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
        at android.os.Bundle.writeToParcel(Bundle.java:1034)
        at android.os.Parcel.writeBundle(Parcel.java:669)
        at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:167)
        at android.os.Parcel.writeTypedList(Parcel.java:1112)
        at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51)
        at android.os.Parcel.writeParcelable(Parcel.java:1363)
        at android.os.Parcel.writeValue(Parcel.java:1268)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:644)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
        at android.os.Bundle.writeToParcel(Bundle.java:1034)
        at android.os.Parcel.writeBundle(Parcel.java:669)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2919)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3296)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.io.NotSerializableException: com.constant.blackpink.ActivityMain
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
        at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
        at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
        at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
        at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
        at android.os.Parcel.writeSerializable(Parcel.java:1389)
        at android.os.Parcel.writeValue(Parcel.java:1341) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:644) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
        at android.os.Bundle.writeToParcel(Bundle.java:1034) 
        at android.os.Parcel.writeBundle(Parcel.java:669) 
        at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:167) 
        at android.os.Parcel.writeTypedList(Parcel.java:1112) 
        at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51) 
        at android.os.Parcel.writeParcelable(Parcel.java:1363) 
        at android.os.Parcel.writeValue(Parcel.java:1268) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:644) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313) 
        at android.os.Bundle.writeToParcel(Bundle.java:1034) 
        at android.os.Parcel.writeBundle(Parcel.java:669) 
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:2919) 
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3296) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by SuddenH4X** [comment]
Hi @kandz,

I reckon that you use one of the listeners with a reference to your `ActivityMain`. And if the app goes in `onPause()` while the dialog is shown, the dialog including the listeners will be serialized and so the `ActivityMain`, which fails.

**Comment by kandz** [comment]
Hi @SuddenH4X 

How to dismiss the dialog & destroy the listener ?

**Comment by SuddenH4X** [comment]
Hi @kandz,

you can simply use `MutableLiveData` to fix this issue. This is also used in the `MainActivity` of the example app to display a toast if you want to take a look.

If you really want to dismiss the dialog you can use the `create()` method of the builder to get the `DialogFragment`. So it's in your hand to display and dismiss the dialog.
